- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/DialogWindowPresenter.class.st
- src/Spec-Core/TickingWindowPresenter.class.st
- src/Spec-Core/WindowPresenter.class.st
- src/Spec-MorphicAdapters/MorphicWindowAdapter.class.st
- src/Spec-MorphicAdapters/SpecDialogWindow.class.st
- src/Spec-MorphicAdapters/WorldPresenter.class.st
- src/Spec-Tests/SpecWindowTest.class.st
New pass on model -> presenter
Fixes https://github.com/pharo-spec/Spec/issues/10
> 10-rename-model-variable-inte-presenter

- src/Spec-Core/WindowPresenter.class.st
Remove WindowPresenter title variable.
Fixes #18
> 18-remove-windowPresenter-title-variable

- src/Spec-Layout/SpecLayoutFrame.class.st
Cut dependency from Spec-Layout to Spec-Core
Fixes #5
> 5-cut-cyclic-dependency

- src/Spec-Core/FastTablePresenter.class.st
- src/Spec-Core/ListPresenter.class.st
- src/Spec-Core/SliderPresenter.class.st
- src/Spec-Core/TreePresenter.class.st
- src/Spec-Layout/SpecLayoutAdd.class.st
- src/Spec-Layout/SpecTableLayoutAddSpacer.class.st
Remove multiple variables and dead code.
Fixes #24
> 24-clean-dead-code

- src/BaselineOfSpec/BaselineOfSpec.class.st
Add dependencies between packages.
Fixes #6
> 6-add-dependencies-between-packages

- src/Spec-Tests/UIThemeDecoratorTest.class.st
Move tests to tests package.
Fixes #27
> 27-Move-tests-to-test-package

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/WindowPresenter.class.st
Remove a questionnable message usage.
Fixes #20
> 20-better-about-title-management

- src/Spec-Core/SpecBindings.class.st
- src/Spec-Core/SpecInterpreter.class.st
Use a default value for SpecBindings
Fixes #55
> 55-Use-default-value-for-bindings

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/DynamicComposablePresenter.class.st
Deprecate #instantiateModels:
Fixes #35
> 35-deprecate-instantiateModels

- src/Spec-Core/ComposablePresenter.class.st
Remove use of #value on additionalKeyBindings that is not a value holder
Fixes #75
> 75-additionalKeyBindings-is-not-a-value-holder

- src/Spec-Core/ContainerPresenter.class.st
- src/Spec-Core/SpecInterpreter.class.st
Remove the need of #buildAdapterWithSpec
Fixes #77
> 77-remove-need-of-overriding-buildAdapterWithSpec

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/DialogWindowPresenter.class.st
- src/Spec-Core/SpecInterpreter.class.st
- src/Spec-Core/WindowPresenter.class.st
Remove some duplication
Fixes #79
> 79-remove-some-duplication

- src/BaselineOfSpec/BaselineOfSpec.class.st
- src/BaselineOfSpec/MCVersionLoader.extension.st
New way to hack the Spec problem
Fixes #85
> 85-make-spec-load-in-non-interactive-alternative

- README.md
> Add install instructions to the README

- src/Spec-Examples/SpecDemo.class.st
Register SpecDemo in the WorldMenu
FIxes #90
> 90-register-spec-demo-in-world-menu

- src/Spec-Layout/SpecLayoutAdd.class.st
Correct dynamic builder
Fixes #112
> 112-correct-dynamic-builder

- src/Spec-MorphicAdapters/MorphicMenuItemAdapter.class.st
> 88-Typo-in-menu-adapter

- src/Spec-Core/AbstractAdapter.class.st
- src/Spec-Core/Object.extension.st
- src/Spec-Core/SpecInterpreter.class.st
Kill Object>>#isSpecAdaptor
Fixes #123
> 123-Kill-isSpecAdator

- src/BaselineOfSpec/BaselineOfSpec.class.st
- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/SpecInterpreter.class.st
- src/Spec-Core/WindowPresenter.class.st
- src/Spec-Deprecated80/ComposablePresenter.extension.st
- src/Spec-Deprecated80/CurrentSpecDefaultBindings.class.st
- src/Spec-Deprecated80/SpecInterpreter.extension.st
- src/Spec-Deprecated80/SpecLayout.extension.st
- src/Spec-Deprecated80/WindowPresenter.extension.st
- src/Spec-Deprecated80/package.st
- src/Spec-Layout/SpecLayout.class.st
Create a Spec-Deprecated80 package.
Fixes #118
> 118-Add-a-Spec-Deprecated80-package

- src/Spec-Core/TextInputFieldPresenter.class.st
- src/Spec-Deprecated80/CurrentSpecDefaultBindings.class.st
- src/Spec-Deprecated80/InputTextDropList.extension.st
- src/Spec-Deprecated80/LabelledInputTextDropList.extension.st
- src/Spec-Deprecated80/LabelledTextInput.extension.st
- src/Spec-Deprecated80/ManifestSpecDeprecated.class.st
- src/Spec-Deprecated80/MorphicTextInputFieldAdapter.extension.st
- src/Spec-Deprecated80/SelectEntity.extension.st
- src/Spec-Deprecated80/TextInputFieldPresenter.extension.st
- src/Spec-Examples/SpecDemoStandaloneFormPresenter.class.st
- src/Spec-Examples/SpecDemoTextInputPresenter.class.st
- src/Spec-Examples/SpecSpacerDemo.class.st
- src/Spec-Examples/TextFieldExample.class.st
- src/Spec-MorphicAdapters/MorphicTextInputFieldAdapter.class.st
- src/Spec-PolyWidgets/InputTextDropList.class.st
- src/Spec-PolyWidgets/LabelledInputTextDropList.class.st
- src/Spec-PolyWidgets/LabelledTextInput.class.st
- src/Spec-PolyWidgets/SearchableList.class.st
- src/Spec-PolyWidgets/SearchableTree.class.st
- src/Spec-PolyWidgets/SelectEntity.class.st
Rename #ghostText to #placefolder un spec to be more independant of Morphic.
Fixes #94
> 94-Rename-ghostText-to-placeholder

- src/Spec-Core/NumberInputFieldPresenter.class.st
- src/Spec-Examples/SpecDemo.class.st
- src/Spec-Examples/SpecDemoFormModel.class.st
- src/Spec-Examples/SpecDemoStandaloneFormPresenter.class.st
- src/Spec-MorphicAdapters/MorphicNumberInputFieldAdapter.class.st
- src/Spec-MorphicAdapters/MorphicTextInputFieldAdapter.class.st
- src/Spec-MorphicAdapters/PluggableTextFieldMorph.extension.st
- src/Spec-StubAdapter/SpecStubNumberInputFieldAdapter.class.st
- src/Spec-StubAdapter/SpecStubNumberInputFieldView.class.st
- src/Spec-Tests/MorphicNumberInputFieldAdapterTest.class.st
- src/Spec-Tests/NumberInputFieldPresenterTest.class.st
This PR includes a first version of the Morphic input number.
FIxes #100
> 100-add-a-NumberPresenter

- src/Spec-Core/ActionBarPresenter.class.st
- src/Spec-Core/ButtonBarPresenter.class.st
- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/DialogWindowPresenter.class.st
- src/Spec-Core/OkCancelToolbar.class.st
- src/Spec-Core/OkToolbar.class.st
- src/Spec-Core/TextPresenter.class.st
- src/Spec-Core/WindowPresenter.class.st
- src/Spec-Examples/PrepareWindowExample.class.st
- src/Spec-MorphicAdapters/MorphicButtonBarAdapter.class.st
- src/Spec-MorphicAdapters/MorphicDialogWindowAdapter.class.st
- src/Spec-MorphicAdapters/MorphicWindowAdapter.class.st
- src/Spec-MorphicAdapters/SpecDialogWindow.class.st
- src/Spec-PolyWidgets/EditableList.class.st
> 132-refactor-DialogWindowPresenter

- resources/migration/specPharo7ToSpecPharo8.md
- src/Spec-Deprecated80/DeprecatedSpecToolbarHelper.class.st
- src/Spec-Deprecated80/DialogWindowPresenter.extension.st
- src/Spec-Deprecated80/OkCancelToolbar.class.st
- src/Spec-Deprecated80/OkToolbar.class.st
Repare the old way to use the dialog toolbar and make it deprecated
Fixes #142
> 142-Add-message-about-how-to-correct-Instance-of-DialogWindowPresenter-did-not-understand-toolbar

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/LabelPresenter.class.st
- src/Spec-Core/LinkPresenter.class.st
- src/Spec-Examples/SpecDemoLinksPage.class.st
- src/Spec-Examples/SpecDemoLinksPresenter.class.st
- src/Spec-MorphicAdapters/MorphicLinkAdapter.class.st
- src/Spec-MorphicAdapters/MorphicTabAdapter.class.st
Create a link presenter with a demo.
Fixes #136
> 136-New-presenter-URL-presenter

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/DialogWindowPresenter.class.st
- src/Spec-Core/ModalWindowPresenter.class.st
- src/Spec-Examples/SpecDemoAbstractModalPresenter.class.st
- src/Spec-Examples/SpecDemoModal1Presenter.class.st
- src/Spec-Examples/SpecDemoModal2Presenter.class.st
- src/Spec-Examples/SpecDemoModalPresenter.class.st
- src/Spec-Examples/SpecDemoModalsPage.class.st
- src/Spec-MorphicAdapters/MorphicModalWindowAdapter.class.st
Add real modals to spec.
Fixes #144
> 144-We-should-have-real-modals-in-Spec

- src/Spec-Core/DialogWindowPresenter.class.st
- src/Spec-Core/WindowPresenter.class.st
- src/Spec-MorphicAdapters/MorphicDialogWindowAdapter.class.st
- src/Spec-MorphicAdapters/MorphicWindowAdapter.class.st
- src/Spec-MorphicAdapters/SpecDialogWindow.class.st
Try to make dialog managment easier by reusing more behavior from windows. 
Fixes #154
> 154-Manage-dialog-more-like-windows

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/ProgressBarFixed.class.st
- src/Spec-Core/ProgressBarIndeterminated.class.st
- src/Spec-Core/ProgressBarPresenter.class.st
- src/Spec-Core/ProgressBarProgressing.class.st
- src/Spec-Core/ProgressBarState.class.st
- src/Spec-Examples/SpecProgressBarDemo.class.st
- src/Spec-Examples/SpecProgressBarDemoPage.class.st
- src/Spec-MorphicAdapters/IndeterminatedProgressBarMorph.class.st
- src/Spec-MorphicAdapters/MorphicProgressBarAdapter.class.st
- src/Spec-MorphicAdapters/ProgressBarFixed.extension.st
- src/Spec-MorphicAdapters/ProgressBarIndeterminated.extension.st
- src/Spec-MorphicAdapters/ProgressBarProgressing.extension.st
- src/Spec-MorphicAdapters/ProgressBarState.extension.st
Finish first version of the progress bar
Fixes #159
> 159-Feature-request-Progress-Bar

- src/Spec-MorphicAdapters/MorphicIconListAdapter.class.st
That was done on Pharo main repository.
See [this PR](https://github.com/pharo-project/pharo/pull/2217).
> Integrate 22890 fix on Spec

- src/Spec-Core/TableBasePresenter.class.st
- src/Spec-Examples/SpecDemoTablePage.class.st
- src/Spec-Examples/SpecDemoTablePresenter.class.st
- src/Spec-Examples/SpecDemoTreeTablePage.class.st
- src/Spec-Examples/SpecDemoTreeTablePresenter.class.st
- src/Spec-Layout/SpecExecutableLayout.class.st
- src/Spec-MorphicAdapters/MorphicTableAdapter.class.st
Implement #beResizable on tables + add demos + fix bug in layouts.
Fixes #189
> 189-Add-beResizable-to-table-presenter

- src/Spec-StubAdapter/SpecStubWindowAdapter.class.st
add empty  SpecStubWindowAdapter>>#close
fixes #202
> 202-SpecStubWindowAdapter-is-missing-close

- src/Spec-MorphicAdapters/MorphicButtonBarAdapter.class.st
- src/Spec-MorphicAdapters/MorphicTableAdapter.class.st
- src/Spec-Tests/TablePresenterTest.class.st
> 205-Table-with-no-columns-throws-strange-error

- src/BaselineOfSpec/BaselineOfSpec.class.st
- src/Spec-Core/TableBasePresenter.class.st
- src/Spec-Pharo7To8Compatibility/NewValueHolder.extension.st
- src/Spec-Pharo7To8Compatibility/package.st
- src/Spec-Tests/TablePresenterTest.class.st
Fix issue #211. Implement Single selection in TablePresenter with tests
> 211-Implement-single-selection-in-TablePresenter

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/SpecInterpreter.class.st
- src/Spec-Layout/SpecExecutableLayout.class.st
- src/Spec-Tests/ComposablePresenterWithAdditionalSubpresentersTest.class.st
- src/Spec-Tests/TestingComposablePresenterWithAdditionalPresenters.class.st
add additionalSubpresentersMap
based on PR for issue 199
fixex #218
> 218-add-support-for-additional-subpresenters-map

- src/Spec-StubAdapter/SpecStubWindowAdapter.class.st
add SpecStubWindowAdapter>>#delete
fixes #228
> 228-SpecStubWindowAdapter-is-missing-delete

- src/Spec-Core/AbstractListPresenter.class.st
- src/Spec-Core/ColumnedListPresenter.class.st
- src/Spec-Core/FastTablePresenter.class.st
- src/Spec-Core/NotebookPage.class.st
- src/Spec-Core/SpecAdapterBindings.class.st
- src/Spec-Core/SpecCollectionListModel.class.st
- src/Spec-Core/SpecInterpreter.class.st
- src/Spec-Core/SpecMultipleSelectionMode.class.st
- src/Spec-Core/SpecPragmaCollector.class.st
- src/Spec-Core/TransferPresenter.class.st
- src/Spec-Examples/SpecDemoFormPresenter.class.st
- src/Spec-Examples/SpecDemoPage.class.st
- src/Spec-Inspector/EyeInspector.class.st
- src/Spec-Inspector/InspectorNavigator.class.st
- src/Spec-Layout/SpecBoxConstraints.class.st
- src/Spec-Layout/SpecGridLayout.class.st
- src/Spec-Layout/SpecLayoutFrame.class.st
- src/Spec-MorphicAdapters/MorphicLinkAdapter.class.st
- src/Spec-MorphicAdapters/MorphicPanedAdapter.class.st
- src/Spec-MorphicAdapters/MorphicStyleSheetProperty.class.st
- src/Spec-MorphicAdapters/MorphicTabManagerAdapter.class.st
- src/Spec-MorphicAdapters/MorphicTreeAdapter.class.st
- src/Spec-MorphicAdapters/MorphicWindowAdapter.class.st
- src/Spec-MorphicAdapters/NotebookMorph.class.st
- src/Spec-MorphicAdapters/SpecDialogWindow.class.st
- src/Spec-Tools/MessageBrowser.class.st
- src/Spec-Tools/VersionBrowser.class.st
> 282-Sync-with-Pharo

- src/Spec-StubAdapter/SpecStubListAdapter.class.st
- src/Spec-StubAdapter/SpecStubWindowAdapter.class.st
fix adapter assignment
fixes #270
> 270-ListPresenter-is-nil-with-SpecStubAdapterBindings

- src/Spec-Examples/SpecDemoButtonsPresenter.class.st
Change layout of Buttons demo
Fixes #272
> 272-Button-demo-is-broken

- src/Spec-MorphicAdapters/AbstractMorphicAdapter.class.st
- src/Spec-StubAdapter/SpecStubAbstractAdapter.class.st
- src/Spec-StubAdapter/SpecStubBoxAdapter.class.st
- src/Spec-StubAdapter/SpecStubBoxView.class.st
- src/Spec-StubAdapter/SpecStubGridAdapter.class.st
- src/Spec-StubAdapter/SpecStubGridView.class.st
- src/Spec-StubAdapter/SpecStubLayoutAdapter.class.st
- src/Spec-StubAdapter/SpecStubPanedAdapter.class.st
- src/Spec-StubAdapter/SpecStubPanedView.class.st
improve stub adapters
fixes #309
fixes #319
> 319-Stub-adapters-for-layouts-are-missing

- src/Spec-MorphicAdapters/MorphicButtonAdapter.class.st
make menus associated with buttons at least partially working
fixes #308
> 308-Button-with-a-menu-is-not-showing-the-menu

- src/Spec-Core/MenuItemPresenter.class.st
- src/Spec-Examples/SpecDemo.class.st
- src/Spec-Examples/SpecDemoLabelledPresenter.class.st
- src/Spec-Examples/SpecDemoStandaloneFormPresenter.class.st
- src/Spec-Examples/SpecDemoTextInputPresenter.class.st
- src/Spec-MorphicAdapters/MorphicButtonAdapter.class.st
- src/Spec-MorphicAdapters/MorphicMenuItemAdapter.class.st
fix deprecated calls
fixes #329
> 329-SpecDemo-deprecation-rewrites

- src/Spec-Deprecated80/ComposablePresenter.extension.st
- src/Spec-Deprecated80/IconListPresenter.class.st
- src/Spec-Deprecated80/MorphicIconListAdapter.class.st
- src/Spec-Deprecated80/MorphicTabAdapter.class.st
- src/Spec-Deprecated80/MorphicTabManagerAdapter.class.st
- src/Spec-Deprecated80/TabManagerPresenter.class.st
- src/Spec-Deprecated80/TabManagerPresenterTest.class.st
- src/Spec-Deprecated80/TabPresenter.class.st
- src/Spec-Deprecated80/TabPresenterTest.class.st
- src/Spec-Deprecated80/TabsExample.class.st
- src/Spec-Deprecated80/TabsExampleTest.class.st
Ensure everything related to tabs is in deprecated.
Fixes #352
> 352-Move-everything-related-to-tab-manager-to-deprecated-package

- src/Spec-Examples/TextFieldExample.class.st
- src/Spec-Tools/MessageBrowser.class.st
MessageBrowser should not use FastTablePresenter.
Fixes #361
> 361-Remove-last-user-of-FastTablePresenter

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Deprecated80/ComposablePresenter.extension.st
- src/Spec-Deprecated80/MorphicMultiColumnListAdapter.class.st
- src/Spec-Deprecated80/MultiColumnListPresenter.class.st
- src/Spec-Tools/KeymapBrowser.class.st
- src/Spec-Tools/VersionBrowser.class.st
Remove users of MultiColumnListPresenter and deprecate it.
It also correct the firtering system of Keymap browser.
Fixes #369
> 369-Remove-users-of-MultiColumnListPresenter-and-deprecate-it

- src/BaselineOfSpec/BaselineOfSpec.class.st
Try atomic loading for Spec.
FIxes #383
> 383-DependencyAnalyzer-is-broken-in-Pharo-8

- src/Spec-Examples/SpecDemo.class.st
- src/Spec-Examples/SpecSpacerDemo.class.st
Fix extent of demos.
Fixes #381
> 381-SpecDemo-window-is-small

- src/BaselineOfSpec/BaselineOfSpec.class.st
- src/BaselineOfSpec/MCVersionLoader.extension.st
Remove baseline hack.
Fixes #387
> 387-Remove-baseline-hack

- src/Spec-Tests/ComposablePresenterWithAdditionalSubpresentersTest.class.st
Test should not let opened windows.
Fixes #390
> 390-ComposablePresenterWithAdditionalSubpresentersTest-leave-opened-window

- src/Spec-Core/SpecApplication.class.st
- src/Spec-MorphicAdapters/MorphicDialogWindowAdapter.class.st
- src/Spec-MorphicAdapters/MorphicModalWindowAdapter.class.st
optional dialog buton bar
fixes #397
> 397-DialogWindowPresenter-buttonBar-should-be-optional

- src/Spec-Core/AbstractListPresenter.class.st
- src/Spec-Core/ListPresenter.class.st
- src/Spec-Core/SpecCollectionListModel.class.st
- src/Spec-Tests/AbstractListPresenterTest.class.st
Implement basics for sorting. 
Fixes #410
> 410-List-presenter-sorting-block-is-ignored

- src/Spec-BackendTests/MillerColumnAdapterTest.class.st
- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/Presenter.class.st
- src/Spec-Core/SpecMillerActivation.class.st
- src/Spec-Core/SpecMillerColumnPresenter.class.st
- src/Spec-Core/SpecMillerPresenter.class.st
- src/Spec-Core/SpecNullMillerPresenter.class.st
- src/Spec-Layout/SpecExecutableLayout.class.st
- src/Spec-MorphicAdapters/MorphicBoxAdapter.class.st
- src/Spec-Tests/MillerColumnPresenterTest.class.st
- src/Spec-Tests/SpecMockMillerPresenter.class.st
Fix #419
First version of miller columns + tests.
This implementation is a first step towards what could be new dynamic spec/layouts, with a nice test foundation.
Remains thinking the scrolling/scoping the number of panes but still this is usable
> 419-Add-Miller-columns

- src/Spec-Core/ComposablePresenter.class.st
Remove broken method.
Fixes #424
> 424-Remove-apiSelectors

- src/Spec-Core/TextInputFieldPresenter.class.st
- src/Spec-Deprecated80/TextInputFieldPresenter.extension.st
- src/Spec-Examples/SpecDemoLabelledPresenter.class.st
- src/Spec-Examples/SpecDemoTextInputPresenter.class.st
- src/Spec-Tests/SpecDemoTest.class.st
- src/Spec-Tests/TextInputFieldPresenterTest.class.st
Fix demo + add test + fix password management in text presenter
Fixes #434
Fixes #435
> 434-Some-demo-pages-are-failing

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Examples/ApplicationWithToolbar.class.st
- src/Spec-Examples/PrepareWindowExample.class.st
- src/Spec-Examples/SpecDemo.class.st
- src/Spec-Examples/SpecDemoButtonsPresenter.class.st
- src/Spec-Inspector/EyeAbstractInspector.class.st
- src/Spec-Tools/DualChangeSorterApplication.class.st
Introduce #newMenu and #newMenubar + add browse to demo
Fixes #438
Fixes #439
> 438-Add-action-to-browse-a-demo-code-from-the-list-of-demos

- src/Spec-Core/AbstractListPresenter.class.st
- src/Spec-Core/SpecAbstractSelectionMode.class.st
- src/Spec-Core/SpecMultipleSelectionMode.class.st
- src/Spec-Core/SpecSingleSelectionMode.class.st
- src/Spec-Core/SpecVersatileDialogPresenter.class.st
- src/Spec-Examples/SpecDemoStandaloneFormPresenter.class.st
- src/Spec-Tests/ListPresenterMultipleSelectionTest.class.st
Fix form demo + add missing features to lists.
Fixes #447
> 447-Form-demo-has-wrong-items-selected-in-list

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/WindowPresenter.class.st
- src/Spec-MorphicAdapters/SpecWindow.class.st
add requestWindowClose
fixes #448
> 448-askOkToClose-seems-to-be-ignored

- src/Spec-BackendTests/AbstractTreeTableAdapterTest.class.st
- src/Spec-Core/AbstractTreeSingleSelectionMode.class.st
- src/Spec-Core/TreeMultipleSelectionMode.class.st
- src/Spec-Core/TreeSingleSelectionMode.class.st
- src/Spec-Core/TreeTablePresenter.class.st
- src/Spec-MorphicAdapters/MorphicTreeTableAdapter.class.st
Fix CI + keep coherence between list and trees for selection
Fixes #451
> 451-CI-is-broken

- src/Spec-Examples/SpecDemo.class.st
- src/Spec-Layout/SpecExecutableLayout.class.st
- src/Spec-MorphicAdapters/MorphicBoxAdapter.class.st
- src/Spec-MorphicAdapters/MorphicGridAdapter.class.st
- src/Spec-MorphicAdapters/MorphicOverlayAdapter.class.st
- src/Spec-MorphicAdapters/MorphicPanedAdapter.class.st
- src/Spec-MorphicAdapters/MorphicScrollableAdapter.class.st
Add a way to rebuild executables layout.
This PR is for the Morphic backend.
Fixes #391
> 391-GridLayout-is-not-able-to-rebuild-itself

- src/Spec-MorphicAdapters/MorphicModalWindowAdapter.class.st
fixes #437
modal window do not react correctly on isOpen
> 437-It-is-not-possible-to-close-modals-anymore

- src/Spec-BackendTests/AbstractAdapterTestCase.class.st
- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/MenuItemPresenter.class.st
- src/Spec-Examples/SpecDemoListsPresenter.class.st
- src/Spec-MorphicAdapters/AbstractMorphicAdapter.class.st
- src/Spec-MorphicAdapters/MorphicMenuGroupAdapter.class.st
Add conditions to menu.
Fixes #463
> 463-Cannot-have-condition-in-menus

- src/Spec-Pharo7To8Compatibility/TAssertable.extension.st
- src/Spec-Pharo7To8Compatibility/TestAsserter.extension.st
Add compatibility methods.
Fixes #474
> 474-Add-assertEmpty-to-P7-compatibility-package

- src/Spec-Core/SpecMillerColumnPresenter.class.st
- src/Spec-Examples/SpecMillerColumnPresenter.extension.st
Fix test on MillerColumn presenter.
Fixes #477
> 477-MillerColumn-tests-are-failing

- src/Spec-Core/NotebookPresenter.class.st
- src/Spec-Examples/SpecDemoListsPresenter.class.st
- src/Spec-MorphicAdapters/MorphicMenuGroupAdapter.class.st
Do not show non visible menus in Morphic.
Fixes #473
> 473-menu-display

- src/Spec-BackendTests/DynamicMockPresenter.class.st
- src/Spec-BackendTests/SpecExecutableLayoutWithDynamicPresenterTest.class.st
- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Examples/SpecDemoCheckboxesPresenter.class.st
- src/Spec-Examples/SpecDemoDynamicMemoryGamePresenter.class.st
Initialize #visible sooner because dynamic builder launches a build sooner than other presenters.
Fixes #481
> 481-Error-while-applying-executable-layouts-in-some-cases

- src/BaselineOfSpec/BaselineOfSpec.class.st
- src/Spec-Deprecated80/FastTablePresenter.class.st
- src/Spec-Deprecated80/MorphicFastTableAdapter.class.st
Add Spec compatibility tests to baseline.
Fixes #484
> 484-Spec-compatibility-tests-are-apparently-not-launched-on-the-CI

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Layout/SpecExecutableLayout.class.st
Improve errors on layout resolution.
Fixes #487
> 487-Impove-error-on-layouts

- src/Spec-MorphicAdapters/MorphicStyleSheetExtent.class.st
> 394-weather---whether

- src/Spec-Core/CheckBoxTableColumn.class.st
- src/Spec-Examples/SpecDemoTablePresenter.class.st
- src/Spec-MorphicAdapters/MorphicTableCellBuilder.class.st
- src/Spec-MorphicAdapters/MorphicTableColumnVisitor.class.st
Add checkbox columns in Morphic. 
Fixes #494
> 494-Introduce-checkbox-column-in-tables

- src/Spec-Core/TreeTablePresenter.class.st
- src/Spec-Tests/TreeTablePresenterTest.class.st
add contextMenu to TreeTablePresenter and test but it's just copy and paste
> 507-add-contextMenu--to-TreeTablePresenter-

- src/Spec-Core/TreeMultipleSelectionMode.class.st
#selectedItems can get the selected items.
> Add "selectedItems" to the TreeMultipleSelectionMode

- src/Spec-MorphicAdapters/AbstractMorphicAdapter.class.st
Fix bug in keystroke simulations.
Fixes #523
> 523-Fix-failing-test

- src/Spec-Core/DropListPresenter.class.st
- src/Spec-Tests/DropListPresenterTest.class.st
I need to use the sort feature so I add some methods about sortBlock in the DropListPresenter
(Refer from AbstractListPresenter)
> Add "sortingBlock" to the DropListPresenter

- src/Spec-Deprecated80/RadioButtonGroupPresenter.class.st
- src/Spec-Examples/CheckBoxExample.class.st
- src/Spec-Examples/RadioButtonExample.class.st
- src/Spec-Examples/RadioButtonGroupExample.class.st
- src/Spec-Examples/SpecDemoCheckboxesPresenter.class.st
- src/Spec-Examples/SpecDemoRadioButtonsPage.class.st
- src/Spec-Examples/SpecDemoRadioButtonsPresenter.class.st
- src/Spec-Tests/RadioButtonExampleTest.class.st
Clean checkboxes and radio buttons examples.
Fixes #528
> 528-Spec-examples-contains-examples-of-deprecated-presenters

- src/Spec-BackendTests/AbstractAdapterTestCase.class.st
- src/Spec-BackendTests/AbstractLayoutTestCase.class.st
- src/Spec-BackendTests/ListCommonPropertiestTest.class.st
- src/Spec-BackendTests/MorphicBackendForTest.class.st
- src/Spec-Core/SpecObservableSlot.class.st
- src/Spec-MorphicAdapters/NotebookMorph.class.st
- src/Spec-Tools/MessageBrowser.class.st
Harvest Pharo changes.
Fixes #531
> 531-Harvest-Pharo-changes

- src/Spec-MorphicAdapters/FTBasicItem.extension.st
Fix #503 
get the right selection
> 503-TreeTablePresenter-whenSelectionChangedDo-gives-the-wrong-selection

- src/Spec-BackendTests/ListCommonPropertiestTest.class.st
- src/Spec-Core/SpecMultipleSelectionMode.class.st
Fix passing from multiple to single list selection
Fixes #559
> 559-ListPresenterbeSingleSelectionbeMultipleSelection-raises-error-

- src/Spec-Core/ComposablePresenter.class.st
- src/Spec-Core/WindowPresenter.class.st
- src/Spec-Deprecated80/ComposablePresenter.extension.st
Add deprecations to everything linked to window in composable presenter and add missing methods to WindowPresenter.
Fixes #562
> 562-Add-deprecations-to-window-methods-of-ComposablePresenter

- src/Spec-Core/AbstractFormButtonPresenter.class.st
- src/Spec-Core/AbstractWidgetPresenter.class.st
- src/Spec-Deprecated80/TreePresenter.class.st
Make all variables of AbstractWidgetPresenter an observable slot.
> Transform-value-holders-into-observable-slots

- src/Spec-Deprecated80/AbstractListPresenter.extension.st
> Fix typo: MeruPresenter -> MenuPresenter

- src/Spec-Core/TablePresenter.class.st
- src/Spec-Examples/SpecDemoNotebookPage.class.st
- src/Spec-Examples/SpecDemoNotebookPresenter.class.st
- src/Spec-Examples/SpecListsDemoPage.class.st
- src/Spec-Examples/SpecProgressBarDemo.class.st
- src/Spec-Examples/SpecProgressBarDemoPage.class.st
> Cleanup comments and typos in Spec-Examples

- src/Spec-BackendTests/AbstractListCommonPropertiestTest.class.st
- src/Spec-BackendTests/AbstractTreeTableAdapterTest.class.st
- src/Spec-Examples/SpecDemoTreeTablePresenter.class.st
- src/Spec-MorphicAdapters/MorphicTreeTableAdapter.class.st
- src/Spec-Tests/TreeTablePresenterTest.class.st
Add tests on menu + fix menu for morphic tree table presenter + improve example
Fixes #581
> 581-TreeTableAdapter-doesNotUnderstand-UpdateMenu

- src/Spec2-Adapters-Morphic/Morph.extension.st
- src/Spec2-Adapters-Morphic/SpMorphicContainerAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicTableContainerAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicWindowAdapter.class.st
- src/Spec2-Core/SpComposablePresenter.class.st
- src/Spec2-Deprecated/SpComposablePresenter.extension.st
- src/Spec2-Deprecated/SpMorphicWindowAdapter.extension.st
Remove #centerWidget: and #centeredRelativeTo:
Fixes #601
> 601-Remove-centerWidget--company

- src/Spec2-Examples/SpClassMethodBrowser.class.st
- src/Spec2-Tests/SpSmokeTestCase.class.st
Harvest Pharo changes.
Fixes #611
> 611-Harvest-changes-from-Pharo

- src/Spec2-Core/SpPresenter.class.st
- src/Spec2-Deprecated/SpOkToolbar.class.st
- src/Spec2-PolyWidgets/SpMethodToolbar.class.st
Remove dead code + migrate layout of SpMethodToolbar
Fixes #619
> 619-addAllwithSpec-is-dead-code

- src/Spec2-Adapters-Morphic/SpMorphicBackend.class.st
- src/Spec2-Adapters-Morphic/SpMorphicDefaultStyleSheet.class.st
- src/Spec2-Adapters-Morphic/SpMorphicStyleSheet.class.st
- src/Spec2-Adapters-Morphic/SpMorphicTextInputFieldAdapter.class.st
- src/Spec2-Adapters-Morphic/SpWorldPresenter.class.st
- src/Spec2-PolyWidgets/SpToolBarButtonMorph.class.st
- src/Spec2-PolyWidgets/SpToolBarMorph.class.st
Reduce references to theme singleton.
Fixes #621
> 621-Reduce-references-to-theme-singleton

- src/Spec2-Core/SpAbstractPresenter.class.st
- src/Spec2-Core/SpVersatileDialogPresenter.class.st
- src/Spec2-Core/TSpDynamicPresenter.trait.st
- src/Spec2-Examples/SpDemoFormPresenter.class.st
- src/Spec2-Examples/SpDemoLabeledContainer.class.st
- src/Spec2-Examples/SpDemoLabelledPresenter.class.st
- src/Spec2-Examples/SpListSelectionPresenter.class.st
- src/Spec2-Examples/SpOpenOnIntExample.class.st
- src/Spec2-Examples/SpOpenOnNilExample.class.st
- src/Spec2-Examples/SpOpenOnStringExample.class.st
- src/Spec2-Examples/SpProgressBarDemo.class.st
- src/Spec2-PolyWidgets/SpEditableList.class.st
- src/Spec2-PolyWidgets/SpLabelledContainer.class.st
- src/Spec2-PolyWidgets/SpLabelledDropList.class.st
- src/Spec2-PolyWidgets/SpLabelledPresenter.class.st
- src/Spec2-PolyWidgets/SpLabelledTextInput.class.st
- src/Spec2-PolyWidgets/SpRGBSliders.class.st
- src/Spec2-PolyWidgets/SpRGBWidget.class.st
- src/Spec2-PolyWidgets/SpSearchableList.class.st
- src/Spec2-PolyWidgets/SpSearchableTree.class.st
- src/Spec2-PolyWidgets/SpSelectEntity.class.st
- src/Spec2-PolyWidgets/SpSliderInput.class.st
Migrate layouts to executable layouts.
Fixes #615
> 615-Migrate-more-layouts-to-executable-layouts

- src/Spec2-Deprecated/SpAbstractTwoButtons.class.st
- src/Spec2-Deprecated/SpAbstractTwoButtonsTest.class.st
- src/Spec2-Deprecated/SpDropListButton.class.st
- src/Spec2-Deprecated/SpDropListButtonTest.class.st
- src/Spec2-Deprecated/SpLabelledDropListButton.class.st
- src/Spec2-Deprecated/SpLabelledDropListButtonTest.class.st
- src/Spec2-Deprecated/SpLabelledInputTextDropList.class.st
- src/Spec2-Deprecated/SpLabelledInputTextDropListTest.class.st
- src/Spec2-Deprecated/SpMorphicSpacerAdapter.class.st
- src/Spec2-Deprecated/SpMorphicTreeAdapter.class.st
- src/Spec2-Deprecated/SpMorphicTreeColumnAdapter.class.st
- src/Spec2-Deprecated/SpMorphicTreeNodeAdapter.class.st
- src/Spec2-Deprecated/SpPickListPresenter.class.st
- src/Spec2-Deprecated/SpPickListPresenterTest.class.st
- src/Spec2-Deprecated/SpRadioButtonGroupPresenter.class.st
- src/Spec2-Deprecated/SpSearchableList.class.st
- src/Spec2-Deprecated/SpSearchableListTest.class.st
- src/Spec2-Deprecated/SpSpacerPresenter.class.st
- src/Spec2-Deprecated/SpTestingAbstractTwoButtons.class.st
- src/Spec2-Deprecated/SpTreeColumnPresenter.class.st
- src/Spec2-Deprecated/SpTreeNodePresenter.class.st
- src/Spec2-Deprecated/SpTreePresenter.class.st
Deprecated Searchable list since we have a filter in lists directly.
Fixes #174
> 174-Deprecate-SearchableList-once-ListPresenter-filtering-will-be-implemented

- src/Spec2-Morphic-Backend-Tests/SpMorphicGridLayoutTests.class.st
Skip failing tests.
Fixes #640
> 640-Skip-failing-tests-for-now

- src/Spec2-Adapters-Morphic/SpMorphicCodeAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicTextAdapter.class.st
- src/Spec2-Core/SpAbstractTextPresenter.class.st
Harvest Pharo changes.
Fixes #645
> 645-Harvest-Pharo-changes

- src/Spec2-Adapters-Morphic/SpMorphicModalWindowAdapter.class.st
- src/Spec2-Examples/SpDemoNotebookPresenter.class.st
Add an example method used by reflectivity + fix bug in modals.
Fixes #649
> 649-Harvest-Pharo-changes

- src/Spec2-Adapters-Morphic/SpNotebookMorph.class.st
- src/Spec2-Core/SpButtonPresenter.class.st
- src/Spec2-Inspector/EyeInspectorNavigator.class.st
- src/Spec2-Tools/ConfigurationGenerator.class.st
Use `ifNil:`,  `ifNotNil:` and `ifNil:ifNotNil:` instead of `isNil` and `ifTrue/ifFalse` combinations
> ifNil and variants usage

- src/Spec2-Tests/SpComposablePresenterWithModelTest.class.st
- src/Spec2-Tests/SpTestingPresenterWithModel.class.st
> 664-SpTestingComposerWithModel-into-SpTestingPresenterWithModel

- src/Spec2-Core/SpAbstractWidgetPresenter.class.st
- src/Spec2-Core/SpPresenter.class.st
> 651-Comment-of-SpPresenter-mentions-ComposablePresenter

- src/Spec2-Adapters-Morphic/SpMorphicListAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicTableAdapter.class.st
- src/Spec2-Backend-Tests/SpAbstractAdapterTestCase.class.st
- src/Spec2-Backend-Tests/SpAbstractListAdapterMultipleSelectionTest.class.st
- src/Spec2-Backend-Tests/SpAbstractListAdapterSingleSelectionTest.class.st
- src/Spec2-Backend-Tests/SpAbstractListCommonPropertiestTest.class.st
- src/Spec2-Backend-Tests/SpAbstractTreeTableAdapterTest.class.st
- src/Spec2-Backend-Tests/SpImageAdapterTest.class.st
- src/Spec2-Backend-Tests/SpListCommonPropertiestTest.class.st
- src/Spec2-Backend-Tests/SpMorphicBackendForTest.class.st
- src/Spec2-Backend-Tests/SpTableCommonPropertiestTest.class.st
- src/Spec2-Deprecated/SpSearchableList.class.st
- src/Spec2-Examples/SpDemoListsPresenter.class.st
- src/Spec2-Examples/SpDemoTreeTablePresenter.class.st
- src/Spec2-PolyWidgets-Tests/SpCalendarPresenterTest.class.st
- src/Spec2-PolyWidgets/SpChooseMethodUI.class.st
- src/Spec2-Tools/MessageBrowser.class.st
This allows to have different backends reusing the tests
> Making tests to use adapters

- src/BaselineOfSpec2/BaselineOfSpec2.class.st
> Now uses v1.1.0 of Commander2.

- src/Spec2-Commander2-ContactBook-Extensions/SpContactBookPresenter.extension.st
- src/Spec2-Commander2-ContactBook/SpContactBookPresenter.class.st
- src/Spec2-Commander2-Tests/SpRecursiveContextSetterTest.class.st
- src/Spec2-Commander2/SpPresenter.extension.st
- src/Spec2-Commander2/SpRecursiveContextSetter.class.st
> 692 commander2 layer should set the presenter as context of commands when not done

- src/Spec2-Core/SpAbstractTextPresenter.class.st
- src/Spec2-Tests/SpTextPresenterTest.class.st
Add #SpApstractTextPresenter>>#clearContent
Fixes #693
> 693-Add-the-method-clearContent-in-the-class-SpAbstractTextPresenter

- src/BaselineOfSpec2/BaselineOfSpec2.class.st
> Fix load errors

- src/Spec2-Core/SpMorphPresenter.class.st
Remove useless method
Fixes #687
> 687-unnecessary-initialize-method-in-SpMorphPresenter

- src/Spec2-Adapters-Morphic/SpMorphicImageAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicMenuAdapter.class.st
- src/Spec2-Core/ManifestSpec2Core.class.st
- src/Spec2-Core/SpAbstractAdapter.class.st
- src/Spec2-Core/SpPresenter.class.st
- src/Spec2-Deprecated/SpMorphicTabAdapter.class.st
- src/Spec2-Deprecated/SpPresenter.extension.st
- src/Spec2-Deprecated/SpRadioButtonGroupPresenter.class.st
- src/Spec2-Deprecated/SpTabPresenter.class.st
- src/Spec2-Help/SpExamples.class.st
- src/Spec2-Help/SpHelpTopics.class.st
- src/Spec2-Help/SpLayouts.class.st
- src/Spec2-Help/SpTheHeartOfSpec.class.st
- src/Spec2-PolyWidgets-Tests/SpLabelledContainerTest.class.st
- src/Spec2-Tests/SpAbstractWidgetLayoutTest.class.st
- src/Spec2-Tests/SpComposablePresenterWithAdditionalSubpresentersTest.class.st
- src/Spec2-Tests/SpInterpreterTest.class.st
- src/Spec2-Tests/SpTestingPresenter.class.st
- src/Spec2-Tests/SpTestingPresenterWithAdditionalPresenters.class.st
Remove all references to ComposablePresenter in comments and variable names
> Remove-ComposablePresenter-references

- src/Spec2-Adapters-Morphic/Morph.extension.st
- src/Spec2-Adapters-Morphic/SpWorldPresenter.class.st
- src/Spec2-Deprecated/Morph.extension.st
- src/Spec2-Deprecated/SpMorphicGenericAdapter.class.st
- src/Spec2-Examples/SpDropListExample.class.st
- src/Spec2-Examples/SpScrollSyncExample.class.st
Deprecate #asSpAdapter.
Fixes #728
> 728-Deprecate-asSpAdapter

- src/BaselineOfSpec2/BaselineOfSpec2.class.st
- src/Spec2-Commander2-Tests/SpMenuPresenterBuilderTest.class.st
Source code transformations due to deprecations.
> 732-Change-dependency-to-Commander2-for-v120

- src/Spec2-Core/SpAbstractFormButtonPresenter.class.st
- src/Spec2-Core/SpAbstractListPresenter.class.st
- src/Spec2-Core/SpAbstractTextPresenter.class.st
- src/Spec2-Core/SpAbstractWidgetPresenter.class.st
- src/Spec2-Core/SpDropListPresenter.class.st
- src/Spec2-Core/SpSliderPresenter.class.st
- src/Spec2-Core/SpTextInputFieldPresenter.class.st
- src/Spec2-Core/SpTextPresenter.class.st
- src/Spec2-Deprecated/SpAbstractListPresenter.extension.st
- src/Spec2-Deprecated/SpAbstractTextPresenter.extension.st
- src/Spec2-Deprecated/SpTreePresenter.class.st
Remove all commented pragmas
Fixes #188
> 188-Remove-all-commented-pragmas

- src/Spec2-Core/SpPresenter.class.st
Introduce #initializePresenters and #connectPresenters.
> Introduce-new-API

- src/Spec2-Adapters-Morphic/SpAbstractMorphicAdapter.class.st
- src/Spec2-Core/SpEditableList.class.st
- src/Spec2-Core/SpLabelledContainer.class.st
- src/Spec2-Core/SpPresenter.class.st
- src/Spec2-Deprecated/SpInputTextDropList.class.st
- src/Spec2-Deprecated/SpInputTextDropList.extension.st
- src/Spec2-Deprecated/SpInputTextDropListTest.class.st
- src/Spec2-Deprecated/SpMorphicGenericAdapter.class.st
- src/Spec2-Examples/SpDemoStandaloneFormPresenter.class.st
- src/Spec2-Examples/SpEditableList.extension.st
Migrate more layouts to executable layouts + deprecate a presenter too specific.
> Migrate-more-layouts

- src/Spec2-Examples/SpDemoTextInputPresenter.class.st
- src/Spec2-Examples/SpDemoTreeTablePresenter.class.st
> Improve-demos

- src/Spec2-Adapters-Morphic/SpMorphicGridLayout.class.st
- src/Spec2-Adapters-Morphic/SpMorphicGridLayoutComputation.class.st
- src/Spec2-Adapters-Morphic/SpStyleGeometry.class.st
- src/Spec2-Core/SpPresenter.class.st
- src/Spec2-Morphic-Backend-Tests/SpMorphicGridLayoutTest.class.st
- src/Spec2-Transmission/SpTransmissionExample.class.st
all tests are green now (that does not means everything work, just that we need more tests)
> fix-grid-layout-tests

- src/Spec2-Commander2-ContactBook/SpRemoveContactCommand.class.st
- src/Spec2-Commander2-ContactBook/SpRenameContactCommand.class.st
Some things were forgotten during the Commander2 migration.
> Commander2-v2-migration

- src/Spec2-Examples/SpBoxLayoutExample.class.st
Start a demo on the box layout. 
This is not finished but it's a least a start.
> Add-demo-on-Box-Layout

- src/Spec2-Adapters-Morphic/SpMorphicButtonAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicMenuButtonAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicWindowAdapter.class.st
- src/Spec2-Core/SpAbstractButtonPresenter.class.st
- src/Spec2-Core/SpButtonPresenter.class.st
- src/Spec2-Core/SpMenuButtonPresenter.class.st
- src/Spec2-Core/SpPresenter.class.st
- src/Spec2-Core/SpWindowPresenter.class.st
- src/Spec2-Examples/SpDemoMenuButtonPresenter.class.st
- src/Spec2-Tests/SpAbstractButtonPresenterTest.class.st
- src/Spec2-Tests/SpButtonPresenterTest.class.st
- src/Spec2-Tests/SpMenuButtonPresenterTest.class.st
- src/Spec2-Tests/SpWindowPresenterTest.class.st
> add-menu-button-presenter

- src/BaselineOfSpec2/BaselineOfSpec2.class.st
- src/Spec2-ObservableSlot/Slot.extension.st
- src/Spec2-ObservableSlot/SpNonObservableSlotError.class.st
- src/Spec2-ObservableSlot/SpObservablePoint.class.st
- src/Spec2-ObservableSlot/SpObservableSlot.class.st
- src/Spec2-ObservableSlot/SpValueHolder.class.st
- src/Spec2-ObservableSlot/TSpObservable.trait.st
- src/Spec2-ObservableSlot/package.st
Move the observable slot to its own package.
> Move-observable-slot-to-its-own-package

- src/Spec2-Adapters-Morphic-Tests/SpStyleTest.class.st
- src/Spec2-Backend-Tests/SpDropListAdapterTest.class.st
- src/Spec2-Core/SpAbstractWidgetPresenter.class.st
- src/Spec2-Core/SpCodePresenter.class.st
- src/Spec2-Core/SpContainerPresenter.class.st
- src/Spec2-Core/SpDropListItem.class.st
- src/Spec2-Core/SpImagePresenter.class.st
- src/Spec2-Core/SpNotebookPresenter.class.st
- src/Spec2-Core/SpPresenter.class.st
- src/Spec2-Core/SpVersatileDialogPresenter.class.st
- src/Spec2-Layout/SpSplitterHorizontal.class.st
- src/Spec2-Layout/SpSplitterVertical.class.st
Do some cleanings needed for Pharo integration
> Cleaning-for-pharo-integration

- src/Spec2-Adapters-Morphic/SpMorphicMenuBarAdapter.class.st
> Deprecation #enabled -> #isEnabled

- src/Spec2-Core/SpMenuGroupPresenter.class.st
- src/Spec2-Core/SpMenuPresenter.class.st
instantiate menu items and groups correclty
fixes #797
> 797-menu-items-do-not-inherit-application

- src/Spec2-Commander2-Tests/SpCommandTest.class.st
- src/Spec2-Commander2/SpCommand.class.st
- src/Spec2-Commander2/SpToolBarPresenterBuilder.class.st
Implemented mechanism to let users specify custom presenters.
Added unit tests for this feature.
Refactored code to use this feature.
> 827-Modify-commander2-integration-to-allow-one-to-specify-custom-presenters

- src/Spec2-Adapters-Morphic/FTBasicItem.extension.st
- src/Spec2-Adapters-Morphic/FTStaticBasicItem.extension.st
- src/Spec2-Adapters-Morphic/FTTreeItem.extension.st
- src/Spec2-Adapters-Morphic/SpMorphicTreeTableDataSource.class.st
- src/Spec2-Backend-Tests/SpAbstractTreeTableAdapterTest.class.st
- src/Spec2-Backend-Tests/SpTreeTableAdapterMultiColumnTest.class.st
- src/Spec2-Backend-Tests/SpTreeTableAdapterSingleColumnMultiSelectionTest.class.st
- src/Spec2-Backend-Tests/SpTreeTableAdapterSingleColumnTest.class.st
- src/Spec2-Core/SpTreeTablePresenter.class.st
- src/Spec2-Morphic-Backend-Tests/SpMorphicTreeTableAdapter.extension.st
Add lazy children tree option with tests.
Needed for https://github.com/pharo-project/pharo-launcher/issues/392
> add-lazy-children-tree-option

- src/BaselineOfSpec2/BaselineOfSpec2.class.st
- src/Spec2-Adapters-Morphic-Tests/SpApplicationTest.extension.st
- src/Spec2-Core/SpPresenter.class.st
- src/Spec2-MorphicPresenters-Tests/SpDatePresenterTest.class.st
- src/Spec2-MorphicPresenters-Tests/SpImageAdapterTest.class.st
- src/Spec2-MorphicPresenters-Tests/SpImagePresenterTest.class.st
- src/Spec2-MorphicPresenters-Tests/SpLinkPresenterTest.class.st
- src/Spec2-MorphicPresenters-Tests/SpRGBSlidersTest.class.st
- src/Spec2-MorphicPresenters-Tests/SpRGBWidgetTest.class.st
- src/Spec2-MorphicPresenters-Tests/SpVersatileDialogPresenterTest.class.st
- src/Spec2-MorphicPresenters-Tests/package.st
- src/Spec2-MorphicPresenters/Form.extension.st
- src/Spec2-MorphicPresenters/SpDatePresenter.class.st
- src/Spec2-MorphicPresenters/SpImagePresenter.class.st
- src/Spec2-MorphicPresenters/SpLinkPresenter.class.st
- src/Spec2-MorphicPresenters/SpMorphPresenter.class.st
- src/Spec2-MorphicPresenters/SpPresenter.extension.st
- src/Spec2-MorphicPresenters/SpRGBSliders.class.st
- src/Spec2-MorphicPresenters/SpRGBWidget.class.st
- src/Spec2-MorphicPresenters/SpSelectEntity.class.st
- src/Spec2-MorphicPresenters/SpVersatileDialogPresenter.class.st
- src/Spec2-MorphicPresenters/SpWorldPresenter.class.st
- src/Spec2-MorphicPresenters/package.st
- src/Spec2-Tests/SpApplicationTest.class.st
add Spec2-MorphicPresenters with all the Morphic dependent presenters
> add Spec2-MorphicPresenters package

- src/Spec2-Core/SpDynamicLeftToRightColumnsLayout.class.st
- src/Spec2-Core/SpDynamicPresentersListLayout.class.st
- src/Spec2-Core/SpDynamicTopToBottomRowsLayout.class.st
Added a constraintsBlock in SpDynamicPresentersListLayout to be able to apply the same constraints to all presenters.
> Added a constraintsBlock in SpDynamicPresentersListLayout

- src/Spec2-Adapters-Morphic/SpMorphicModalWindowAdapter.class.st
Allow the closing of modal dialogs 
See https://github.com/pharo-project/pharo/issues/7032 and  https://github.com/pharo-project/pharo/pull/7033
> Missing super

- src/Spec2-Adapters-Morphic/SpMorphicNotebookAdapter.class.st
- src/Spec2-Adapters-Morphic/SpNotebookMorph.class.st
- src/Spec2-Core/SpNotebookPage.class.st
- src/Spec2-Examples/SpDemoNotebookPresenter.class.st
Fix to #806.
Not sure if it's the best solution, but to me it looks evident that nobody was using `beCloseable` and this makes it work.
> Notebook: can't add a closable page

- src/Spec2-Layout/SpMillerLayout.class.st
> 900-Typo-in-SpMillerLayout-class-comment

- src/Spec2-Tools-Tests/SpChooseMethodPresenterTest.class.st
- src/Spec2-Tools/SpChangeSorterPresenter.class.st
- src/Spec2-Tools/SpChooseMethodPresenter.class.st
- src/Spec2-Tools/SpDualChangeSorterPresenter.class.st
- src/Spec2-Tools/SpKeymapPresenter.class.st
Fixes: #908 rename KeympaBrowser -> SpKeymapPresenter, ChangeSorter -> SpChangeSorterPresenter, Dual -> SpDual..Presenter, ChooseMethodUI -> SpChooseMethodPresenter + clean class comments
> 908-SpChooseMethodUI-should-be-renamed-SpChooseMethodPresenter

- src/Spec2-Core/SpDropListItem.class.st
- src/Spec2-Core/SpDropListPresenter.class.st
- src/Spec2-Core/SpLabelledDropList.class.st
- src/Spec2-Core/SpLabelledList.class.st
- src/Spec2-Core/SpListPresenter.class.st
Fixes: #906 add comment to display: and displayAt:
> 906-Can-we-have-a-comment-for-the-method-display-in-spPresenterList

- src/Spec2-Core/SpAbstractPresenter.class.st
- src/Spec2-Core/SpDialogWindowPresenter.class.st
Fixes: #887 starting to add comments and hoping that they are correct!
> 887-change-comment-of-openDialogWithSpec

- spec2.md
> Fixed typos on spec2.md

- src/Spec2-Adapters-Morphic/SpMorphicTextAdapter.class.st
> Added value call if menuPresenter is a block

- src/Spec2-Core/SpListWithFilterPresenter.class.st
- src/Spec2-Core/SpPresenter.class.st
- src/Spec2-Tests/SpListWithFilterPresenterTest.class.st
> Added SpListWithFilterPresenter and SpListWithFilterPresenterTest

- src/Spec2-Transmission/SpInputPort.class.st
- src/Spec2-Transmission/SpOutputPort.class.st
> SpInputPort and SpOutputPort should be abstract

- src/Spec2-Tools/ManifestSpec2Tools.class.st
> Class comment for ManifestSpec2Tools

- src/Spec2-Tools/AbstractMessageCentricBrowser.class.st
> Cleanup of AbstractMessageCentricBrowser

- src/Spec2-Tools/SpKeymapPresenter.class.st
> Cleanup SpKeymapPresenter

- src/Spec2-Tools/SpChooseMethodPresenter.class.st
> Cleanup SpChooseMethodPresenter

- src/Spec2-Tools/ChangeSorterModel.class.st
- src/Spec2-Tools/SpChangeSorterPresenter.class.st
- src/Spec2-Tools/SpDualChangeSorterPresenter.class.st
> Cleanups in Spec2 change sorters

- src/Spec2-Transmission/SpAbstractPort.class.st
- src/Spec2-Transmission/SpInputPort.class.st
- src/Spec2-Transmission/SpOutputPort.class.st
> SpPort should be SpAbstractPort

- src/Spec2-Code-Commands/SpCodeDebugItCommand.class.st
- src/Spec2-Code-Commands/SpCodeDoItCommand.class.st
- src/Spec2-Code-Commands/SpCodeInspectItCommand.class.st
- src/Spec2-Code-Commands/SpCodePrintItCommand.class.st
- src/Spec2-Code-Commands/SpCodeProfileItCommand.class.st
- src/Spec2-Code-Commands/SpCodeSelectionCommand.class.st
> Cleanup Spec2-Code-Commands

- src/Spec2-Adapters-Morphic/MillerScrollPane.class.st
- src/Spec2-Adapters-Morphic/SpMorphicBoxAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicGridAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicGridLayoutComputation.class.st
- src/Spec2-Adapters-Morphic/SpMorphicLayoutAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicMillerAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicOverlayAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicPanedAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicPanedLayout.class.st
- src/Spec2-Adapters-Morphic/SpMorphicScrollableAdapter.class.st
- src/Spec2-Adapters-Morphic/SpPanedResizerMorph.class.st
- src/Spec2-Adapters-Morphic/SpPanedResizerVerticalMorph.class.st
- src/Spec2-Adapters-Morphic/SpTableLayout.class.st
>  Cleanup package Spec-Adapters-Morphic - PART 2

- src/Spec2-Adapters-Morphic/SpDragAndDropTransferToTree.class.st
- src/Spec2-Adapters-Morphic/SpMorphicTreeTableAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicTreeTableDataSource.class.st
Add drag&drop support for trees in the Morphic backend
> Add tree drag&drop support

- src/Spec2-Adapters-Morphic-Tests/SpMergeStyleTest.class.st
- src/Spec2-Adapters-Morphic/SpStyleClass.class.st
Improving the merging of stylesheets when they have the same class.
So, the resulting style has a combination of classes and properties.
> improving-merge-of-stylesheets

- src/Spec2-Adapters-Morphic/SpMorphicMenuItemAdapter.class.st
Fix https://github.com/pharo-vcs/iceberg/issues/1409
> The printing of the shortcuts should delegate in the KMShortcutPrinter.

- src/Spec2-Layout/SpPanedLayout.class.st
another step to fix the #testNoUnusedInstanceVariablesLeft
> remove the unused ivars in SpPanedLayout

- src/Spec2-Backend-Tests/SpFilteringListSelectableAdapterTest.class.st
- src/Spec2-Code/SpCodeNullInteractionModel.class.st
- src/Spec2-Code/SpCodePopoverErrorPresenter.class.st
- src/Spec2-Core/SpTextPresenter.class.st
- src/Spec2-Morphic-Tests/SpTestWorldPresenter.class.st
> remove some  more unused ivars

- src/Spec2-Adapters-Morphic/SpMorphicTreeTableDataSource.class.st
- src/Spec2-Core/SpTreeTablePresenter.class.st
Fixes this issue in pharo: https://github.com/pharo-project/pharo/issues/8421
> Fixes tree table indentation problem (Pharo issue 8421)

- src/Spec2-Code/SpCodePresenter.class.st
- src/Spec2-Tests/SpCodePresenterTest.class.st
This is the code from https://github.com/pharo-project/pharo/pull/8462 that got lost
This fixes https://github.com/pharo-project/pharo/issues/8886
> SpCodePresenter-selectedSelector

- src/Spec2-Adapters-Morphic/SpMorphicLabelAdapter.class.st
- src/Spec2-Adapters-Morphic/SpMorphicSpinnerAdapter.class.st
- src/Spec2-Examples/SpDemoMenuButtonPresenter.class.st
remove unused ivars is SpMorphicLabelAdapter, SpMorphicSpinnerAdapter and SpDemoMenuButtonPresenter
> remove unused ivars is SpMorphicLabelAdapter, SpMorphicSpinnerAdapter and SpDemoMenuButtonPresenter

- src/Spec2-Dialogs/SpInformDialog.class.st
> SpInformDialog has an ivar that is not used --> remove

- src/Spec2-Adapters-Morphic-Tests/SpStyleVariableTest.class.st
- src/Spec2-Adapters-Morphic/SpStyleEnvironmentColorVariable.class.st
- src/Spec2-Adapters-Morphic/SpStyleEnvironmentFontVariable.class.st
- src/Spec2-Adapters-Morphic/SpStyleEnvironmentVariable.class.st
- src/Spec2-Adapters-Morphic/SpStyleResetVariable.class.st
- src/Spec2-Adapters-Morphic/SpStyleVariableEnvironment.class.st
- src/Spec2-Adapters-Morphic/SpStyleVariableEnvironmentColor.class.st
- src/Spec2-Adapters-Morphic/SpStyleVariableEnvironmentFont.class.st
- src/Spec2-Adapters-Morphic/SpStyleVariableReset.class.st
Classes included in this PR are better named with Variable at the end Since They present environment variables.
> Renaming classes of environment variables

- src/Spec2-Tests/SpTestingPresenterWithAdditionalPresenters.class.st
SpTestingPresenterWithAdditionalPresenters has an ivar that is not used --> remove
>  SpTestingPresenterWithAdditionalPresenters has an ivar that is not used 

- src/Spec2-Examples/SpDemoStandaloneFormPresenter.class.st
restor uncommented code, fixes 1046 and https://github.com/pharo-project/pharo/issues/9117
(I am not sure if that is the right fix, but it makes it work for me)
> 1046-Examples-breaks-httpsgithubcompharo-projectpharoissues9117 
