pharo-spec/Spec

src/Spec-Core/ComposablePresenter.class.st, src/Spec-Core/ContainerPresenter.class.st, src/Spec-Core/CurrentSpecDefaultBindings.class.st, src/Spec-Core/ManifestSpecCore.class.st, src/Spec-Core/SpecBindings.class.st, src/Spec-Core/SpecInterpreter.class.st, src/Spec-Tests/SpecInterpreterTest.class.st
- Rename dynamic variable for spec bindings
- Remove useless class instance variable
- Remove default system where the default was always used
- Some more cleanings
Fixes #38
=> 38-begin-interpreter-cleaning

src/Spec-Core/ComposablePresenter.class.st, src/Spec-Core/ContainerPresenter.class.st, src/Spec-Core/DynamicComposablePresenter.class.st, src/Spec-Core/SpecInterpreter.class.st, src/Spec-Core/SpecWrapper.class.st, src/Spec-Layout/SpecLayout.class.st
Remove SpecLayout selector variable. This commit also clean the Interpreter to remove the usage of the useless variable
Fixes #46
=> 46-remove-selector-from-SpecLayout

src/Spec-Core/ComposablePresenter.class.st, src/Spec-Core/ContainerPresenter.class.st, src/Spec-Core/DialogWindowPresenter.class.st, src/Spec-Core/MenuGroupPresenter.class.st, src/Spec-Core/SpecInterpreter.class.st, src/Spec-Core/WindowPresenter.class.st, src/Spec-Tests/SpecInterpreterTest.class.st, src/Spec-Tests/TestingComposablePresenter.class.st
Some cleaning of the interpreter.
This also remove one sender of Object>>#asWidget and a hack to create Morph from the Spec directly.
Fixes #48
=> 48-remove-duplication-in-interpreter

src/Spec-Core/WindowPresenter.class.st
Correct bug in WindowPresenter (value was already called by the getter).
Fixes #50
=> 50-correct-bug-in-window-presenter

src/Spec-Core/SpecInterpreter.class.st
Remove an useless check in the interpreter. 
Fixes #60
=> 60-remove-useless-check-in-interpreter

src/Spec-Core/ComposablePresenter.class.st, src/Spec-Inspector/InspectorNavigator.class.st
Rename defaultWindowModelClass into defaultWindowPresenterClass
Fixes #36
=> 36-rename-more-model-into-presenter

resources/migration/specPharo7ToSpecPharo8.md
Add a migration guide for what is already done in the updated Spec.
Related to #98
=> 98-begin-migration-guide

src/Spec-Core/SpecInterpreter.class.st, src/Spec-Tests/SpecInterpreterTest.class.st, src/Spec-Tests/SpecMockPesenterWithoutGetter.class.st
Do not force the user to have getters for its presenters all the time. We can access the variables.
Fixes #97 and as bonus Fixes #96
=> 97-do-not-force-to-have-getters-in-presenters

src/Spec-Core/ComposablePresenter.class.st
Use a special icon in browser for the presenters. 
Fixes #31
=> 31-use-special-icon-for-presenters

src/Spec-Layout/AbstractSpecLayoutAction.class.st, src/Spec-Layout/SpecLayout.class.st, src/Spec-Layout/SpecLayoutAdd.class.st, src/Spec-Layout/SpecLayoutAddColumn.class.st, src/Spec-Layout/SpecLayoutAddRow.class.st, src/Spec-Layout/SpecLayoutAddWithSpec.class.st, src/Spec-Layout/SpecLayoutSend.class.st, src/Spec-Layout/SpecSplitterHorizontal.class.st, src/Spec-Layout/SpecSplitterVertical.class.st, src/Spec-Layout/SpecTableLayout.class.st, src/Spec-Layout/SpecTableLayoutAdd.class.st, src/Spec-Layout/SpecTableLayoutAddSpacer.class.st, src/Spec-Layout/SpecTableLayoutAddWithSpec.class.st, src/Spec-Layout/SpecTableLayoutSend.class.st
Remove the #arguments variable and direcly compute it when needed.
I runned all the tests and openned the interfaces in the image and it seems to have no impact. I also benched the tests and there is almost no difference. 
Fixes #103
=> 103-speclayout-arguments-variable-seems-useless

src/Spec-Layout/SpecColumnLayout.class.st, src/Spec-Layout/SpecLayout.class.st, src/Spec-Layout/SpecRowLayout.class.st
Remove the need of the #result and #shouldCheckSplitters inst variables.
Those variables are useless because they are just used internally in few methods.
Fixes #110
=> 110-remove-some-useless-variables

src/Spec-Core/ComposablePresenter.class.st, src/Spec-Core/ManifestSpecCore.class.st
Deprecate ComposablePresenter>>#icon: to use #iconNamed:
Fixes #116
=> 116-Clean-icon-management

src/Spec-Core/AbstractWidgetPresenter.class.st, src/Spec-Core/LabelPresenter.class.st, src/Spec-Core/ListPresenter.class.st, src/Spec-Core/TreePresenter.class.st
Replace usage of `Smalltalk ui theme`.
Fixes #119
=> 119-Remove-use-of-Smalltalk-ui-theme-in-presenters

src/Spec-Core/AbstractWidgetPresenter.class.st, src/Spec-Core/MenuPresenter.class.st, src/Spec-Core/SpecInterpreter.class.st, src/Spec-Examples/CheckBoxExample.class.st, src/Spec-Examples/MethodBrowser.class.st, src/Spec-Layout/SpecLayoutAdd.class.st, src/Spec-Layout/SpecLayoutAddWithSpec.class.st, src/Spec-Tests/SpecInterpreterTest.class.st, src/Spec-Tools/MonticelloRepositoryBrowser.class.st, src/Spec-Tools/WorkingCopyToolBar.class.st
We should be able to use #prensenter instead of #model in layouts.
Fixes #70
=> 70-We-should-be-able-to-use-presenter-instead-of-model-in-layouts

src/Spec-MorphicAdapters/MorphicTabManagerAdapter.class.st
MorphicTabManagerAdaptor does not need to call #asWidget
FIxes #125
=> 125-MorphicTabManagerAdaptor-does-not-need-to-call-asWidget

src/Spec-Core/TabPresenter.class.st, src/Spec-Examples/SpecDemoPage.class.st, src/Spec-Examples/TabsExample.class.st
Tab presenter and Tab example do not need to call #asWidget.
Fixes #129
=> 129-TabPresenter-is-too-corelated-to-Morph

src/Spec-Examples/SpecDemoPage.class.st, src/Spec-Examples/SpecDemoSpacerPage.class.st, src/Spec-Examples/SpecSpacerDemo.class.st
Add a tab with the code of examples in demo.
Fixes #93
=> 93-Add-source-code-in-a-tab-in-the-demo

src/Spec-Core/ProgressBarProgressing.class.st, src/Spec-Core/TextInputFieldPresenter.class.st, src/Spec-MorphicAdapters/ProgressBarProgressing.extension.st
Remove reintroduced deprecated method.
=> 185-ProgressPresenter-should-use-progression-and-not-progressionBlock

src/Spec-Examples/SpecDemoPage.class.st
Use the Notebook presenter in the demo to avoid deprecation warnings.
Fixes #276
=> 276-Demo-should-use-the-Notebook-presenter-instead-of-the-TabManager

src/Spec-Core/AbstractListPresenter.class.st, src/Spec-Core/SpecAbstractSelectionMode.class.st, src/Spec-Core/SpecCollectionListModel.class.st, src/Spec-Core/SpecSingleSelectionMode.class.st, src/Spec-Tests/AbstractListPresenterTest.class.st
ensure when replacing a list, an event is thrown
Fixes #280
=> 280-ListPresenter-does-not-triggers-an-event-when-items-change

src/Spec-StubAdapter/SpecStubButtonView.class.st, src/Spec-StubAdapter/SpecStubCheckBoxView.class.st, src/Spec-StubAdapter/SpecStubContainerView.class.st, src/Spec-StubAdapter/SpecStubDialogWindowView.class.st, src/Spec-StubAdapter/SpecStubDiffView.class.st, src/Spec-StubAdapter/SpecStubDropListView.class.st, src/Spec-StubAdapter/SpecStubFastTableView.class.st, src/Spec-StubAdapter/SpecStubIconListView.class.st, src/Spec-StubAdapter/SpecStubImageView.class.st, src/Spec-StubAdapter/SpecStubListView.class.st, src/Spec-StubAdapter/SpecStubMenuGroupView.class.st, src/Spec-StubAdapter/SpecStubMenuItemView.class.st, src/Spec-StubAdapter/SpecStubMenuView.class.st, src/Spec-StubAdapter/SpecStubMultiColumnListView.class.st, src/Spec-StubAdapter/SpecStubNumberInputFieldView.class.st, src/Spec-StubAdapter/SpecStubRadioButtonView.class.st, src/Spec-StubAdapter/SpecStubSliderView.class.st, src/Spec-StubAdapter/SpecStubSpacerView.class.st, src/Spec-StubAdapter/SpecStubTabManagerView.class.st, src/Spec-StubAdapter/SpecStubTabView.class.st, src/Spec-StubAdapter/SpecStubTableContainerView.class.st, src/Spec-StubAdapter/SpecStubTextInputFieldView.class.st, src/Spec-StubAdapter/SpecStubTextView.class.st, src/Spec-StubAdapter/SpecStubTickingWindowView.class.st, src/Spec-StubAdapter/SpecStubTransferView.class.st, src/Spec-StubAdapter/SpecStubTreeColumnView.class.st, src/Spec-StubAdapter/SpecStubTreeNodeView.class.st, src/Spec-StubAdapter/SpecStubTreeView.class.st, src/Spec-StubAdapter/SpecStubView.class.st, src/Spec-StubAdapter/SpecStubWindowView.class.st
rename SpecStubViews and add empty bindKeyCombination:toAction: to it
fixes #286
fixes #285
=> 286-SpecStubViews-should-be-SpecStubView

src/Spec-Tests/TextPresenterTest.class.st
Split a test in two to explicit what we are testing.
Fixes #289
=> 289-TextPrensenterTesttestSelectAll-should-be-split

src/Spec-Tests/SpecObservableSlotTest.class.st
Observables tests should not be in Core.
Fixes #292
=> 292-Move-all-tests-in-test-package

src/Spec-Inspector/EyeInspector.class.st, src/Spec-PolyWidgets/EditableList.class.st, src/Spec-PolyWidgets/SelectEntity.class.st, src/Spec-Tools/ChangeSorterApplication.class.st
Replace usage of FastTablePresenter to use ListPresenter.
There is still one user but it uses a table and not a list...
Fixes #344
=> 344-Remove-users-of-FastTablePresenter-to-use-ListPresenter

src/Spec-Core/AbstractAdapter.class.st, src/Spec-Core/ComposablePresenter.class.st, src/Spec-Core/RadioButtonGroupPresenter.class.st, src/Spec-Core/SpecInterpreter.class.st, src/Spec-Layout/SpecLayoutFrame.class.st, src/Spec-MorphicAdapters/MorphicListAdapter.class.st, src/Spec-Tests/SpecInterpreterTest.class.st
- add owner to the objects that SpecInterpreter can instantiate (adapters, layout frame)
- clean forgotten halt
- some automatic rewrites
=> 380-Objects-that-the-SpecInterpreter-creates-should-have-an-owner

src/Spec-Core/WindowPresenter.class.st, src/Spec-Deprecated80/MorphicWindowAdapter.extension.st, src/Spec-Deprecated80/SpecStubAbstractAdapter.extension.st, src/Spec-Deprecated80/WindowPresenter.extension.st, src/Spec-MorphicAdapters/MorphicDialogWindowAdapter.class.st, src/Spec-MorphicAdapters/MorphicWindowAdapter.class.st, src/Spec-MorphicAdapters/WorldPresenter.class.st, src/Spec-StubAdapter/SpecStubAbstractAdapter.class.st, src/Spec-StubAdapter/SpecStubWindowAdapter.class.st
Fix name consistency to remove #model and use #presenter.
Fixes #347
=> 347-addModelInwithSpecLayout-methods-should-be-renamed

src/Spec-MorphicAdapters/SpecListFastTableDataSource.class.st
When there is no menu, data source should return nil and not self.
Fixes #412
=> 412-Right-click-on-a-list-produce-an-error

src/Spec-MorphicAdapters/MorphicDefaultStyleSheet.class.st
List should fill verticaly by default. 
Fixes #417
=> 417-List-presenter-does-not-take-all-height-in-horizontal-paned-layout

src/Spec-Core/ComposablePresenter.class.st, src/Spec-Core/DropListPresenter.class.st, src/Spec-Core/DropListSelectionPresenterPort.class.st, src/Spec-Core/ListSelectionPresenterPort.class.st, src/Spec-Core/OutputPresenterPort.class.st, src/Spec-Core/PresenterTransmission.class.st, src/Spec-Examples/TransmissionExample.class.st
Add post transmissions and improve transmissions applications.
- It is now possible to give a post transmission valuable (See issue https://github.com/pharo-spec/Spec/issues/430)
- Now the user can apply transmissions himself, possibly via syntaxic suggar (#from:to:transform: or #from:to:transform:postTransmission:)
- Remove useless variables and rename methods to more conventional names now that they are simpler
Fixes #431
Fixes #430
=> 431-Improve-transmission-application

src/Spec-Examples/SpecDemo.class.st, src/Spec-Examples/SpecDemoPage.class.st, src/Spec-Examples/SpecDemoStandaloneFormPresenter.class.st, src/Spec-Tests/SpecDemoTest.class.st
This commit fix the global demo and add a test.
I also add a test as expected failure that all the demo pages do not raise an error but it does not pass yet. I'll see to fix it in another PR.
Fixes #400
=> 400-Demo-crash-the-image

src/Spec-Core/AbstractWidgetPresenter.class.st, src/Spec-Layout/SpecAbstractWidgetLayout.class.st, src/Spec-Tests/SpecAbstractWidgetLayoutTest.class.st
Do not use the Interpreter to adapt widget presenters.
Fixes #455
=> 455-Remove-usage-of-interpreter-to-adapt-AbstractWidgetPresenters

src/Spec-BackendTests/AbstractLayoutTestCase.class.st, src/Spec-BackendTests/MockDynamicPresenter.class.st, src/Spec-BackendTests/SpecExecutableLayoutTest.class.st, src/Spec-Layout/SpecExecutableLayout.class.st, src/Spec-Tools/ChangeSorterPresenter.class.st, src/Spec-Tools/DualChangeSorterPresenter.class.st
Fix dynamic rebuild in case it was never built + add tests.
Bonus: Fix a bug on the title of the dual code changes.
Fixes #461
=> 461-Dynamic-rebuild-fail-with-executable-layout-if-its-required-before-the-first-opening

src/Spec-BackendTests/NotebookAdapterTest.class.st, src/Spec-Core/NotebookPage.class.st, src/Spec-Core/NotebookPresenter.class.st, src/Spec-Examples/SpecDemoNotebookPage.class.st, src/Spec-Examples/SpecDemoNotebookPresenter.class.st, src/Spec-MorphicAdapters/MorphicNotebookAdapter.class.st, src/Spec-MorphicAdapters/NotebookMorph.class.st, src/Spec-MorphicAdapters/NotebookTabSelectorMorph.class.st, src/Spec-MorphicBackendTests/MorphicNotebookAdapter.extension.st, src/Spec-Tests/NotebookPresenterTest.class.st
Work on Notebook presenter.
- Add possibility to use a non default spec
- Add/Remove page
- Add presenter and backend tests
- Improve API 
- Fix programmatic selection 
Fixes #466
Fixes #468
Fixes #226
=> 466-Cannot-addremove-page-to-Notebook

src/BaselineOfSpec/BaselineOfSpec.class.st
In Pharo 7 we need to recompile the code after loading Spec 2.
Fixes #471
=> 471-Pharo-7-CI-is-timeouting

src/Spec-MorphicAdapters/MorphicLabelAdapter.class.st
Change the default value of LabelMorph min width.
Fixes #476
=> 476-Executable-presenters-do-not-manage-well-long-labels

src/Spec-Core/AbstractListPresenter.class.st, src/Spec-Deprecated80/AbstractListPresenter.extension.st, src/Spec-Deprecated80/MenuMorph.extension.st
Correct context menu using morphs to ease transition to Spec2.
Fixes #489
=> 489-Do-not-break-backward-compatibility-on-menus

src/Spec-Tests/CodePresenterTest.class.st
Fix test of code presenter context menu
Fixes #519
=> 519-CodePresenterTesttestContextMenu-is-failing

src/Spec-BackendTests/CodeAdapterTest.class.st, src/Spec-BackendTests/TextAdapterTest.class.st
Is `self adapter` instead of asking the presenter.
Fixes #521
=> 521-Some-backend-tests-should-use-the-adapter-method

src/Spec-Deprecated80/RadioButtonGroup.class.st, src/Spec-Deprecated80/RadioButtonGroupPresenter.class.st
Remove call of deprecated method.
Fixes #525
=> 525-canDeselectByClick-is-deprecated-but-still-used

src/Spec-BackendTests/ListCommonPropertiestTest.class.st, src/Spec-Core/AbstractListPresenter.class.st, src/Spec-Core/SpecCollectionListModel.class.st, src/Spec-MorphicAdapters/MorphicListAdapter.class.st
Ensure the list is updated if the user add a filter or disable it.
Fixes #534
=> 534-ItemFilterBlock-update-on-open-list-does-not-update-the-list

src/Spec-Core/AbstractListPresenter.class.st, src/Spec-Core/SpecCollectionListModel.class.st, src/Spec-Deprecated80/AbstractListPresenter.extension.st, src/Spec-Deprecated80/LabelledList.extension.st, src/Spec-Inspector/EyeInspector.class.st, src/Spec-PolyWidgets-Tests/SearchableListTest.class.st, src/Spec-PolyWidgets/EditableList.class.st, src/Spec-PolyWidgets/LabelledList.class.st, src/Spec-PolyWidgets/SearchableList.class.st, src/Spec-Tools/MessageBrowser.class.st
Remove broken filtering system and clean code.
We discussed this with Julien and with Esteban and we agree that initial filtering should be managed by the user and not spec to reduce code complexity. Spec should only manage the final user filtering of the list and not initial filtering.
Fixes #538 
Fixes #537
=> 538-ListPresenter-filteringBlock-is-broken

src/Spec-Deprecated80/MorphicCodeAdapter.extension.st, src/Spec-Inspector/EyeAbstractInspector.class.st, src/Spec-Inspector/EyeInspector.class.st, src/Spec-Inspector/EyePointerExplorer.class.st, src/Spec-Inspector/EyeTreeInspector.class.st, src/Spec-MorphicAdapters/MorphicCodeAdapter.class.st, src/Spec-MorphicAdapters/MorphicTextAdapter.class.st, src/Spec-MorphicAdapters/RubScrolledTextMorph.extension.st, src/Spec-Pharo7To8Compatibility/SpecRubScrolledTextMorph.class.st
Remove dependency on RubPluggableTextMorph
It also fix direct interaction of the inspector on morph.
Fixes #541
=> 541-Spec-should-not-use-RubPluggableTextMorph

src/Spec-BackendTests/CodeAdapterTest.class.st, src/Spec-BackendTests/MorphicCodeAdapter.extension.st, src/Spec-Core/AbstractTextPresenter.class.st, src/Spec-Core/CodePresenter.class.st, src/Spec-Deprecated80/AbstractTextPresenter.extension.st, src/Spec-Deprecated80/CodePresenter.extension.st, src/Spec-Examples/MethodBrowser.class.st, src/Spec-Inspector/EyeAbstractInspector.class.st, src/Spec-MorphicAdapters/MorphicCodeAdapter.class.st, src/Spec-Tests/CodePresenterTest.class.st, src/Spec-Tools/ChangeSorterModel.class.st, src/Spec-Tools/ChangeSorterPresenter.class.st, src/Spec-Tools/MessageBrowser.class.st
Now updating the value of #syntaxHighlight update the rubric open instances.
I also migrated the Spec tools using #aboutToStyle: and I cleaned a little the ChangeSorterModel. 
I also fixed a bug in the ChangeSorter were some text was highlighted when it should not have been.
Fixes #540
=> 540-withwithoutSyntaxHighligh-should-be-observable-and-update-the-adaptor

src/Spec-Core/AbstractTreeSingleSelectionMode.class.st
Its subclasses have to implement this method.
=> Add the #selectPaths to AbstractTreeSingleSelectionMode

src/Spec-Pharo7To8Compatibility/RubTextFieldArea.extension.st
More backward compatibility
Fixes #554
=> 554-Pharo-7-WSL-RubTextFieldAreaObjectdoesNotUnderstand-wrapped

src/Spec-BackendTests/MockDynamicPresenter.class.st, src/Spec-Core/SpecVersatileDialogPresenter.class.st, src/Spec-Deprecated80/AbstractTwoButtons.class.st, src/Spec-Deprecated80/DropListButton.class.st, src/Spec-Examples/InputTextDropList.extension.st, src/Spec-Examples/LabelledContainer.extension.st, src/Spec-Examples/LabelledDropList.extension.st, src/Spec-Examples/LabelledList.extension.st, src/Spec-Examples/LabelledSliderInput.extension.st, src/Spec-Examples/LabelledTextInput.extension.st, src/Spec-Examples/RGBSliders.extension.st, src/Spec-Examples/RGBWidget.extension.st, src/Spec-Examples/SliderInput.extension.st, src/Spec-PolyWidgets/CalendarPresenter.class.st, src/Spec-PolyWidgets/RGBSliders.class.st, src/Spec-PolyWidgets/RGBWidget.class.st, src/Spec-Tests/SpecVersatileDialogPresenterTest.class.st, src/Spec-Tests/SpecWindowTest.class.st, src/Spec-Tools/MessageBrowser.class.st
Remove call to deprecated methods.
Fixes #564
=> 564-Remove-call-to-deprecated-window-methods

src/Spec-Core/AbstractFormButtonPresenter.class.st, src/Spec-Core/AthensAnimatedPresenter.class.st, src/Spec-Core/AthensStaticPresenter.class.st, src/Spec-Core/ComponentListPresenter.class.st, src/Spec-Core/ComposablePresenter.class.st, src/Spec-Core/ImagePresenter.class.st, src/Spec-Core/Presenter.class.st, src/Spec-Core/TablePresenter.class.st, src/Spec-Core/TreeTablePresenter.class.st
Subclasses of Presenter do not need to use TSpecObservable.
Fixes #566
=> 566-TSpecObservable-is-used-by-classes-which-have-a-superclass-already-using-it

src/Spec-Core/ToolBarButton.class.st, src/Spec-Core/ToolBarItemPresenter.class.st, src/Spec-Core/ToolBarLabel.class.st, src/Spec-Core/ToolBarOptionButtonGroup.class.st, src/Spec-Core/ToolBarToggleButton.class.st
Remove useless methods and variables.
Fixes #568
=> 568-ToolBar-classes-implement-help-mechanism-already-present-in-superclass

src/Spec-BackendTests/ImageAdapterTest.class.st, src/Spec-Core/ImagePresenter.class.st, src/Spec-MorphicAdapters/MorphicImageAdapter.class.st, src/Spec-MorphicBackendTests/MorphicImageAdapter.extension.st, src/Spec-Tests/ImagePresenterTest.class.st
Add tests + image presenter should update when we change the autoscale parameter.
Fixes #575
=> 575-autoScale-in-ImagePresenter-not-changeable

src/Spec2-Pharo7To8Compatibility/FTBasicItem.extension.st, src/Spec2-Pharo7To8Compatibility/LayoutFrame.extension.st
Move extensions methods that are now in Pharo directly in the compatibility package.
Fixes #597
=> 597-Remove-extensions-methods-that-are-now-in-Pharo-8

src/Spec2-Adapters-Morphic/Morph.extension.st, src/Spec2-Adapters-Morphic/SpAbstractMorphicAdapter.class.st, src/Spec2-Adapters-Morphic/SpMorphicWindowAdapter.class.st, src/Spec2-Core/SpWindowPresenter.class.st, src/Spec2-Deprecated/Morph.extension.st, src/Spec2-Deprecated/SpAbstractMorphicAdapter.extension.st, src/Spec2-Deprecated/SpMorphicWindowAdapter.extension.st, src/Spec2-Deprecated/SpWindowPresenter.extension.st, src/Spec2-Examples/SpDatePresenter.extension.st
Move everything related to #setModal: in deprecated.
+ Rename conflicting extensions.
Fixes #599
=> 599-Finish-cleaning-of-modal-

src/Spec2-Adapters-Morphic/SpMorphicAdapterBindings.class.st, src/Spec2-Adapters-Stub/SpStubAdapterBindings.class.st
Remove #defaultFont on adapter bindings.
Fixes #53
=> 53-Adapters-bindings-default-fonts-methods-are-not-used

src/Spec2-Adapters-Morphic/SpMorphicModalWindowAdapter.class.st
Fix DropListMorph in modals. 
Fixes #629
=> 629-ModalWindowPresenter-Does-not-allow-to-expand-dropList

src/Spec2-Commander2/SpCommandGroup.class.st, src/Spec2-Deprecated/SpCommandGroup.extension.st
Fix #694 
- Renamed #asToolBarPresenter -> #asToolbarPresenter with deprecation to ease migration.
- Renamed #asToolBarPresenterWith: -> #asToolbarPresenterWith: with deprecation to ease migration.
=> Did some renaming to remove typos from method names.

src/Spec2-Commander2-ContactBook/SpContactBookPresenter.class.st, src/Spec2-Commander2/SpAbstractListPresenter.extension.st, src/Spec2-Commander2/SpAbstractTextPresenter.extension.st, src/Spec2-Commander2/SpButtonPresenter.extension.st, src/Spec2-Commander2/SpTreeTablePresenter.extension.st
Introduced #contextMenuFromCommandsGroup: method that wrap the repetitive code required to convert a group of command as a MenuPresenter.
Fix #704
=> 704-Commander2-should-provide-easier-way-to-use-command-group-on-list-tree-etc

src/Spec2-Commander2/SpDisableWhenCantBeRun.class.st, src/Spec2-Commander2/SpHideWhenCantBeRun.class.st, src/Spec2-Commander2/SpShortcutInstaller.class.st
Replaced #canBeRun with #canBeExecuted.
Fixes #717
=> 717-Fix-calls-to-canBeRun-and-replace-them-with-canBeExecuted

src/Spec2-Commander2/SpPresenter.extension.st
Created #defaultCommandsContext that returns the presenter.
Can be overidden to change the default context set recursively to commands.
Fixes #716
=> 716-Allows-one-to-change-the-default-context-set-on-commands-when-their-context-is-nil

src/Spec2-Commander2-Tests/SpCommandTest.class.st, src/Spec2-Commander2/SpCommand.class.st
Created #asButtonPresenter and tests.
The implementation does not handle when command can not be executed yet because the required strategy does not exist yet.
This will be done later.
Fixes #720
=> 720-Implement-method-to-convert-spec-command-as-ButtonPresenter

src/Spec2-Layout/SpExecutableLayout.class.st
Rename SpExecutableLayout>>#resolvePresenter:model:bindings: into SpExecutableLayout>>#resolvePresenter:presenter:bindings
Fixes #709
=> 709-SpExecutableLayoutresolvePresentermodelbindings-should-be-SpExecutableLayoutresolvePresenterpresenterbindings

src/Spec2-Commander2/CmCommand.extension.st, src/Spec2-Commander2/CmCommandGroup.extension.st
Did the move, these methods are not in Commander2 repository anymore.
Fixes #724
=> 724-Move-spec-related-methods-on-class-side-of-CmCommand-and-CmCommandGroup-to-spec-integration-package

src/Spec2-Pharo7To8Compatibility/SpRubScrolledTextMorph.class.st
Compatibility for Pharo 7 with TextPresenter 
FIxes #730
=> 730-TextPresenter-placeholder-does-not-work-in-Pharo-7

src/Spec2-Adapters-Morphic/SpMorphicModalWindowAdapter.class.st, src/Spec2-Adapters-Morphic/UITheme.extension.st, src/Spec2-Examples/SpDemo.class.st, src/Spec2-Examples/SpDemoStandaloneFormPresenter.class.st
Do not hardcode backdrop color.
Fixes #647
=> 647-Use-theme-instead-of-hardcoded-color-in-Modal-adapter

src/Spec2-Adapters-Morphic/SpMorphicWindowAdapter.class.st, src/Spec2-Core/SpWindowPresenter.class.st, src/Spec2-Deprecated/SpWindowPresenter.extension.st
Rename hasToolBar into hasToolbar.
Fixes #689
=> 689-should-use-toolbar-and-not-toolBar

src/Spec2-Adapters-Morphic/SpMorphicBackend.class.st, src/Spec2-Core/SpApplication.class.st, src/Spec2-Core/SpPresenter.class.st
Required to update the UI properly in Iceberg (Spec 2 version) PullRequestsBrowser.
The aim is to able to fork a process that will fetch the needed data to then ask the presenter to properly updates it's state in the right thread.
=> Adding the ability to defer a UI rendering operation to the backend.

src/Spec2-Adapters-Morphic/SpMorphicLinkAdapter.class.st, src/Spec2-Core/SpLinkPresenter.class.st, src/Spec2-Examples/SpDemoLinksPresenter.class.st, src/Spec2-Tests/SpLinkPresenterTest.class.st
Add possibility to use action with links.
This will allow us to be able to browse classes for example with a link.
Fixes #181
=> Add-possiblity-to-pass-action-to-link-presenter

src/BaselineOfSpec2/BaselineOfSpec2.class.st, src/Spec2-Commander2-ContactBook-Extensions/SpChangePhoneCommand.class.st, src/Spec2-Commander2-ContactBook-Extensions/SpContactBookPresenter.extension.st, src/Spec2-Commander2-ContactBook-Extensions/SpInspectContactCommand.class.st, src/Spec2-Commander2-ContactBook/SpAddContactCommand.class.st, src/Spec2-Commander2-ContactBook/SpContactBookPresenter.class.st, src/Spec2-Commander2-ContactBook/SpPrintContactBookInTranscript.class.st, src/Spec2-Commander2-ContactBook/SpRemoveContactCommand.class.st, src/Spec2-Commander2-ContactBook/SpRenameContactCommand.class.st
- Set dependency to Commander2 v2.x.x floating version
- Adapted commander2 commands parts of Spec2 to use the new API introduced in Commander v2.0.0.
Fixes #734
=> 734-Migrate-Spec-to-use-Commander2-v200

src/Spec2-Core/SpAbstractAdapter.class.st, src/Spec2-Core/SpAbstractFormButtonPresenter.class.st, src/Spec2-Core/SpAbstractPresenter.class.st, src/Spec2-Core/SpAbstractTextPresenter.class.st, src/Spec2-Core/SpAbstractWidgetPresenter.class.st, src/Spec2-Core/SpPresenter.class.st
Add #isAbstract methods in Spec2-Core
Fixes #758
=> 758-SpAbstractPresenter-should-be-abstract

src/BaselineOfSpec2/BaselineOfSpec2.class.st, src/Spec2-Adapters-Morphic-Tests/SpStyleTest.class.st, src/Spec2-Adapters-Morphic-Tests/package.st, src/Spec2-Adapters-Morphic/SpStyleSTONReader.class.st
Having a class with the same name of the elements in the STON breaks the parsing.
=> Fixing issue #787.

src/BaselineOfSpec2/BaselineOfSpec2.class.st, src/Spec2-Backend-Tests/SpMorphicBackendForTest.class.st, src/Spec2-Backend-Tests/SpTMorphicUIRedrawer.trait.st, src/Spec2-Morphic-Backend-Tests/SpPresenterFocusOrderTest.class.st
Remove dependency on Glamour.
We already copied some code of Glamour in Spec. To avoid to have 3 time the same code in Pharo I extracted it in a trait used by spec. (I did not update Glamour since we plan to remove it)
Maybe later this trait should go in Morphic tests?
=> Remove-dependency-on-Glamour

src/Spec2-Layout/SpNonObservableSlotError.class.st, src/Spec2-Layout/SpObservablePoint.class.st, src/Spec2-Layout/SpObservableSlot.class.st, src/Spec2-Layout/SpValueHolder.class.st, src/Spec2-Layout/TSpObservable.trait.st
Move observable slots to Layouts since they use it. It's not the ideal place but they will be extracted from Spec in the end so it will be ok for now.
=> Layouts-should-not-depend-on-Core

src/Spec2-Code/SpCodePresenter.class.st
It looks like #allowingContextMenu, introduced as part of the fix for issue #933, had its sense accidentally backward.
=> Reverse sense of #allowingContextMenu

src/Spec2-Layout/SpExecutableLayout.class.st
Find a child layout that contains a presenter of given key. Useful if you need to find a parent layout of a presenter that you need to replace.
=> parentLayoutOf

src/Spec2-Core/SpFilteringListPresenter.class.st, src/Spec2-Tests/SpFilteringListPresenterTest.class.st
It was a bug in which when changing the items of the filteringList the filter functionality stops working. For example, if you do `SpFilteringListPresenter new items: anItems`. Typing something in the filter box and thn the setting new items `filteringList items: newItems`. The filter functionality stops working. The bug was fixed.
Also, the class name of the tests was wrong. It did not have the same name as the presenter class. And added more test cases to the test class.
=> Fixed bug on SpFilteringListPresenter and also changed tests class name

src/Spec2-Core/SpFilteringListPresenter.class.st, src/Spec2-Tests/SpFilteringListPresenterTest.class.st
It was a bug: When changing the items of a spFilteringList that already had items, the filter functionality stops working.
For example, if you do `SpFilteringListPresenter new items: anItems`. Typing something in the filter box and then setting the new items `filteringList items: newItems`. The filter functionality stops working. The bug was fixed.
Also, the instance variable name of filterInput was changed to filterInputBlock.
And finally, the test for the filterListItems; method now is more detailed.
=> Fixed bug in SpFilteringListPresenter

src/Spec2-Code-Commands/SpCodeDebugItCommand.class.st, src/Spec2-Code-Morphic/SpMorphicCodeAdapter.class.st
Fixes integration between SpCodePresenter and morphic widget to properly setup a requestor for related compilation operations:
- debugIt command
- code highlighting
It fixes the visibility of workspace variables in debugIt expressions and allows further improvement to have transparent temps.
The fix requires extra PR for NewTools to have an effect: https://github.com/pharo-spec/NewTools/pull/122.
=> Fix visibility of workspace variables in debugIt expressions

src/Spec2-Adapters-Morphic/SpAbstractMorphicWindowAdapter.class.st, src/Spec2-Core/SpWindowPresenter.class.st
Adding to the MorphicWindowAdapter the responsibility to handle the change of the toolbar in the presenter.
When a new toolbar is set, we need to replace the old one.
Fix #1013 
Fix https://github.com/pharo-vcs/iceberg/issues/1416
Fix https://github.com/pharo-vcs/iceberg/issues/1407
=> 1013-Changing-a-Toolbar-should-affect-the-window

src/Spec2-Tests/SpTestPresenterWithToolbar.class.st
remove the unused class var from SpTestPresenterWithToolbar
fixes #1012
=> 1012-SpTestPresenterWithToolbar-has-class-var-that-is-not-referenced

src/Spec2-Code/SpCodePresenter.class.st
Senders and implementors should not select the line
- they should take the token that corresponds to the selection or cursor position
- they then should try to check for classes or methods defined using that token/symbol
(+ refactored a bit to avoid code duplications)
=> Fix implementors and senders to work as in Pharo 8

src/Spec2-Adapters-Morphic/SpToolbarButtonMorph.class.st, src/Spec2-Adapters-Morphic/SpToolbarMorph.class.st, src/Spec2-Core/SpToolbarDisplayModeIconAndLabel.class.st
The border style of the toolbar button should not have style different than the one when it is in normal state.
Having additional border makes it bigger and it moves, producing a flick.
The SpToolbarMorph should be rigid vertically and spaceFill horizontally to honor the values set has height by the SpToolbarDisplayMode
The extent when the SpToolbarDisplayModeIconAndLabel should be square.
Fix https://github.com/pharo-vcs/iceberg/issues/1431
=> fixing-moving-buttons-in-toolbar

src/Spec2-Core/SpErrorNotificationType.class.st, src/Spec2-Core/SpInfoNotificationType.class.st, src/Spec2-Core/SpNotificationType.class.st, src/Spec2-Core/SpNotificationTypeError.class.st, src/Spec2-Core/SpNotificationTypeInfo.class.st
SpNotificationTypeError is not an error itself but a notification of type error.
SpNotificationTypeInfo is not an information either but a notification of type information.
=> Rename SpNotificationType hierarchy.

src/Spec2-Adapters-Morphic/SpHorizontalLayoutDirection.extension.st, src/Spec2-Adapters-Morphic/SpVerticalLayoutDirection.extension.st, src/Spec2-Layout/SpHorizontalLayoutDirection.class.st, src/Spec2-Layout/SpLayoutDirection.class.st, src/Spec2-Layout/SpLayoutDirectionHorizontal.class.st, src/Spec2-Layout/SpLayoutDirectionVertical.class.st, src/Spec2-Layout/SpVerticalLayoutDirection.class.st
Renaming the SpLayoutDirection to end with the 'LayoutDirection' is better for consistency reasons of course
=> Rename SpLayoutDirection hierarchy

src/Spec2-Core/SpPopoverBottomPosition.class.st, src/Spec2-Core/SpPopoverLeftPosition.class.st, src/Spec2-Core/SpPopoverPosition.class.st, src/Spec2-Core/SpPopoverPositionBottom.class.st, src/Spec2-Core/SpPopoverPositionLeft.class.st, src/Spec2-Core/SpPopoverPositionRight.class.st, src/Spec2-Core/SpPopoverPositionTop.class.st, src/Spec2-Core/SpPopoverRightPosition.class.st, src/Spec2-Core/SpPopoverTopPosition.class.st
The hierarchy becomes consistent if the 'Position' suffix is placed at the end of all subclasses + class names make more sens.
Example: SpPopoverBottomPosition makes more sens than SpPopoverPositionBottom
=> Rename SpPopoverPosition hierarchy.

src/Spec2-Core/SpToolbarItemLeftPosition.class.st, src/Spec2-Core/SpToolbarItemPosition.class.st, src/Spec2-Core/SpToolbarItemPositionLeft.class.st, src/Spec2-Core/SpToolbarItemPositionRight.class.st, src/Spec2-Core/SpToolbarItemRightPosition.class.st
SpToolbarItemRightPosition and SpToolbarItemLeftPosition make more sens than SpToolbarItemPositionRight and SpToolbarItemPositionLeft respectively + coherent .
=> Renaming SpToolbarItemPosition hierarchy.

src/Spec2-Core/SpIconAndLabelToolbarDisplayMode.class.st, src/Spec2-Core/SpIconToolbarDisplayMode.class.st, src/Spec2-Core/SpLabelToolbarDisplayMode.class.st, src/Spec2-Core/SpToolbarDisplayMode.class.st, src/Spec2-Core/SpToolbarDisplayModeIcon.class.st, src/Spec2-Core/SpToolbarDisplayModeIconAndLabel.class.st, src/Spec2-Core/SpToolbarDisplayModeLabel.class.st
Adding the 'ToolbarDisplayMode' at the end is better :) 
Subclasses of SpToolbarDisplayMode represent modes
=> Rename SpToolbarDisplayMode hierarchy

src/Spec2-Commander2/SpInvalidUserInputError.extension.st, src/Spec2-Interactions/SpInvalidUserInput.class.st, src/Spec2-Interactions/SpInvalidUserInputError.class.st
SpInvalidUserInputError name makes it easier and quicker to understand that the class is an Error raised in case the user enters an invalid input
=> Renaming SpInvalidUserInput to SpInvalidUserInputError

src/Spec2-Commander2/SpCancelledInteractionError.extension.st, src/Spec2-Interactions/SpCancelledInteractionError.class.st, src/Spec2-Interactions/SpInteractionCancelled.class.st, src/Spec2-Interactions/SpPresenter.extension.st
SpCancelledInteractionError is closer in meaning to an error raised when an interaction is cancelled + consistent with the hierarchy
=> Renaming SpInteractionCancelled to SpCancelledInteractionError

src/Spec2-Morphic-Backend-Tests/SpMorphicAdapterTest.class.st, src/Spec2-Morphic-Backend-Tests/SpMorphicAdapterTestCase.class.st
This is the only test class which ends with the case suffix. It would be more consistent to end all test classes with the same Test suffix.
=> Renaming SpMorphicAdapterTestCase to SpMorphicAdapterTest
